spring:
  application:
    name: eureka-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true       # Enables routing via service names
          lowerCaseServiceId: true
      routes:
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog/**

        - id: shopping-cart
          uri: lb://SHOPPING-CART
          predicates:
            - Path=/cart/**

        - id: orders-service
          uri: lb://ORDERS-SERVICE
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
  filter:
    enabled : false