server:
  port: 8082
spring:
  application:
    name: order-query-service

  data:
    mongodb:
      uri: mongodb+srv://sa:admin@vayinala.ddubq5g.mongodb.net/?retryWrites=true&w=majority&appName=
      database: order-query-db

  kafka:
    bootstrap-servers: 3.110.89.80:9092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: com.example.order_query_service.events.OrderCreatedEvent
