server:
  port: 8082
spring:
  application:
    name: order-query-service

  data:
    mongodb:
      uri: mongodb+srv://sa:sa@vayinala.ddubq5g.mongodb.net/?retryWrites=true&w=majority&appName=vayinala
      database: order-query-db

  kafka:
    bootstrap-servers: <EC2_KAFKA_IP>:9092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
