server:
  port: 8081
spring:
  application:
    name: order-command-service

  kafka:
    bootstrap-servers: <EC2_KAFKA_IP>:9092
    consumer:
      group-id: order-command-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    url: jdbc:h2:mem:orders
    driver-class-name: org.h2.Driver
    username: sa
    password: password

    h2:
      console:
        enabled: true
      database-platform: org.hibernate.dialect.H2Dialect
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
            format_sql: true

logging:
    level:
        org.springframework.kafka: INFO
        org.apache.kafka: INFO
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
