spring:
  application:
    name: orders-service
  datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

cart:
  service:
    url: http://SHOPPING-CART/cart

payment:
  service:
    url: http://PAYMENT-SERVICE/payment

resilience4j:
  circuitbreaker:
    instances:
      paymentServiceCB:
        slidingWindowSize: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        record-exceptions:
          - java.lang.IllegalStateException
          - java.lang.RuntimeException
